### ISSUE TITLE
按照默认的配置进行了部署 报错如下

### ISSUE THREAD

**Issue by gladstonejay** [wosyingjun/beauty_ssm#2]
七月 25, 2016 5:51:43 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [spring-dispatcher] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException
    at com.yingjun.ssm.exception.GlobalExceptionResolver.resolveException(GlobalExceptionResolver.java:32)
    at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1183)

**Comment by wosyingjun** [comment]
GlobalExceptionResolver这个类有bug，已经修复。
